# Updates the content submodule using a pull request
name: Update content

on:
    repository_dispatch:
        types: [update_content]

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: 'recursive'

            - name: Update git user
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Update Content
              run: |
                  previous_content_sha=$(git submodule status | awk '{ print substr($1,2) }')
                  echo "previous_content_sha=${previous_content_sha}" >> $GITHUB_ENV

                  git submodule update --remote --merge
                  git add .

                  content_sha=$(git submodule status | awk '{ print substr($1,2) }')
                  echo "content_sha=${content_sha}" >> $GITHUB_ENV

                  git commit -m "Update content to latest commit `labs/main`"

            - name: Close previous Pull Request
              continue-on-error: true
              run: |
                  gh pr close update-content/${{ env.previous_content_sha }} --comment "There is a newer pull-request available." --delete-branch

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  delete-branch: true
                  author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
                  branch: 'update-content/${{ env.content_sha }}'
                  title: 'Update content submodule'
                  labels: update content
                  base: main
                  body: |
                      The content has been updated to the latest commit inf-lab-dev/labs@${{ env.content_sha }} from the [labs](https://github.com/inf-lab-dev/labs) repository.
